import = [
  "~/.config/alacritty/catpuccin-mocha.toml",
  "~/.config/alacritty/font.toml",
  "~/.config/alacritty/extra.toml",
]

[cursor.style]
blinking = "On"
shape = "Block"

[scrolling]
history = 10000
multiplier = 3
